services:

  python-workspace:
    build:
      context: .
      dockerfile: python3.Dockerfile
      args:
        - USER_NAME=${USER}
    volumes:
      - ../..:/workspaces:cached      
    command: sleep infinity

  ollama-service:
    build:
      context: .
      dockerfile: ollama.Dockerfile